### ISSUE TITLE
Can't deploy Seedstack application on AdoptOpenJDK 11.0.9.1

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/seedstack-maven-plugin#15]
On the 12th of November AdoptOpenJDK released a new Java 11 version 11.0.9.1. We are using Docker images to deploy our applications with "FROM adoptopenjdk/openjdk11:alpine-jre" which use the latest version of AdoptOpenJDK.

On this new version it is impossible to deploy Seedstack packaged applications (using Capsule) because this throw the error :

```

CAPSULE EXCEPTION: Could not parse version: 11.0.9.1 while processing attribute Min-Update-Version: {}

java.lang.IllegalArgumentException: Could not parse version: 11.0.9.1
at Capsule.parseJavaVersion(Capsule.java:4259)
at Capsule.getMinUpdateFor(Capsule.java:2635)
at Capsule.isMatchingJavaVersion(Capsule.java:2625)
at Capsule.chooseJavaHome0(Capsule.java:2568)
at Capsule.chooseJavaHome(Capsule.java:2559)
at Capsule.getJavaHome(Capsule.java:2543)
at Capsule.getJavaExecutable0(Capsule.java:2267)
at Capsule.getJavaExecutable(Capsule.java:2259)
at Capsule.buildJavaProcess(Capsule.java:2217)
at Capsule.buildProcess0(Capsule.java:1530)
at Capsule.buildProcess(Capsule.java:1521)
at Capsule.prelaunch0(Capsule.java:1494)
at Capsule.prelaunch(Capsule.java:1487)
at Capsule.prepareForLaunch(Capsule.java:1339)
at Capsule.launch(Capsule.java:1268)
at Capsule.main0(Capsule.java:399)
at Capsule.main(Capsule.java:379)
```

I'm working around the issue right now by creating the Docker images with "FROM adoptopenjdk/openjdk11:jdk-11.0.9_11-alpine" instead but this prevent us from having recent Java minor updates and security fixes.

**Comment by Nyamiou** [comment]
The issue is back. AdoptOpenJDK just recently released the version 11.0.14.1.
