### ISSUE TITLE
No Jansi support on FreeBSD

### ISSUE THREAD

**Issue by dereckson** [seedstack/seedstack-maven-plugin#5]
When trying to build a test web application following http://seedstack.org/getting-started/tutorial/ on a FreeBSD development server, `mvn org.seedstack:seedstack-maven-plugin:run` throws an exception.

The build process with `mvn clean install` works perfectly fine.

According fusesource/jansi-native#5, Jansi doesn't support FreeBSD.

**Stacktrace**

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.seedstack.maven.LauncherRunnable.launch(LauncherRunnable.java:66)
        at org.seedstack.maven.LauncherRunnable.run(LauncherRunnable.java:47)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi64-1.11 in java.library.path, no jansi-1.11 in java.library.path, no jansi in java.library.path]
        at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
        at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
        at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:37)
        at org.seedstack.seed.core.internal.init.ConsoleManager.isTTY(ConsoleManager.java:95)
        at org.seedstack.seed.core.internal.init.ConsoleManager.wrapOutputStream(ConsoleManager.java:51)
        at org.seedstack.seed.core.internal.init.ConsoleManager.install(ConsoleManager.java:27)
        at org.seedstack.seed.core.Seed.init(Seed.java:150)
        at org.seedstack.seed.core.Seed.createKernel(Seed.java:72)
        at org.seedstack.seed.web.internal.SeedServletContainerInitializer.onStartup(SeedServletContainerInitializer.java:34)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:184)
        at org.seedstack.seed.undertow.internal.UndertowLauncher.launch(UndertowLauncher.java:36)
        ... 7 more

**Comment by michael-o** [comment]
With my changes proposed to jansi, it will run out of the box on FreeBSD 9 and 10.

**Comment by adrienlauer** [comment]
Thanks for reporting the issue, I just noticed it now sorry. I look forward to be able to upgrade the jansi version for FreeBSD support but for now I settled for catching any exception that could arise in the detection process while disabling color. This should cover any other unsupported OS.

This was fixed in seedstack/seed#207 which will only be released in version 3.0.0 in november, unless you need it before. In that case, just comment on this issue or on seedstack/seed#206 and I will release it.

**Comment by michael-o** [comment]
This is actually ridiculous, I have provided all necessary help to the Jansi devs to resolve the issue, they simply did not react.
